# Generated by Django 4.2.11 on 2024-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cameraVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=100)),
                ('registration_year', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('rto', models.CharField(max_length=100, null=True)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100, null=True)),
                ('manufacturer_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('distributor_name', models.CharField(max_length=100, null=True)),
                ('owner_address', models.CharField(max_length=100, null=True)),
                ('distributor_address', models.CharField(max_length=100, null=True)),
                ('camera_serial_number_primary', models.CharField(max_length=100, null=True)),
                ('camera_serial_number_secondary', models.CharField(max_length=100, null=True)),
                ('camera_serial_number_tertiary', models.CharField(max_length=100, null=True)),
                ('model_number_primary', models.CharField(max_length=100, null=True)),
                ('model_number_secondary', models.CharField(max_length=100, null=True)),
                ('model_number_tertiary', models.CharField(max_length=100, null=True)),
                ('model_number_quaternary', models.CharField(max_length=100, null=True)),
                ('part_number', models.CharField(max_length=100, null=True)),
                ('drawing_number', models.CharField(max_length=100, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=100, null=True)),
                ('did_no_primary', models.CharField(blank=True, max_length=100, null=True)),
                ('did_no_secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('did_no_tertiary', models.CharField(blank=True, max_length=100, null=True)),
                ('sim_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_network', models.CharField(blank=True, max_length=100, null=True)),
                ('Vehicle_number_plate_view', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('Camera_image', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('Sensor_image', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('Display_image', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gpsVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('gps_serial_no', models.CharField(max_length=100)),
                ('gps_model', models.CharField(max_length=100)),
                ('registration_date', models.IntegerField()),
                ('engine_no', models.CharField(max_length=100)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('registration_no', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100)),
                ('location_primary', models.CharField(max_length=100)),
                ('location_secondary', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_address', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=100)),
                ('registration_year', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('rto', models.CharField(max_length=100, null=True)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100, null=True)),
                ('manufacturer_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('distributor_name', models.CharField(max_length=100, null=True)),
                ('owner_address', models.CharField(max_length=100, null=True)),
                ('distributor_address', models.CharField(max_length=100, null=True)),
                ('camera_serial_number_primary', models.CharField(max_length=100, null=True)),
                ('model_number_primary', models.CharField(max_length=100, null=True)),
                ('camera_serial_number_secondary', models.CharField(max_length=100, null=True)),
                ('model_number_secondary', models.CharField(max_length=100, null=True)),
                ('Vehicle_number_plate_view', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('Camera_image', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('Sensor_image', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('Display_image', models.ImageField(null=True, upload_to='vehicle_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
