# Generated by Django 5.0.4 on 2024-06-26 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rtoapp", "0002_alter_gpsvehicle_chassis_no_alter_gpsvehicle_dealer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cameravehicle",
            old_name="vehicle_no",
            new_name="camera_vehicle_no",
        ),
    ]
