# Generated by Django 5.0.4 on 2024-06-26 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rtoapp", "0003_rename_vehicle_no_cameravehicle_camera_vehicle_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cameravehicle",
            old_name="camera_vehicle_no",
            new_name="vehicle_no",
        ),
    ]
