# Generated by Django 5.0.4 on 2024-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rtoapp", "0004_rename_camera_vehicle_no_cameravehicle_vehicle_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpsvehicle",
            name="registration_date",
            field=models.IntegerField(),
        ),
    ]
