# Generated by Django 4.2.11 on 2024-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0005_alter_gpsvehicle_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsvehicle',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
