# Generated by Django 4.2.11 on 2024-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0006_gpsvehicle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsvehicle',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
