# Generated by Django 4.2.11 on 2024-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0007_alter_gpsvehicle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameravehicle',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gpsvehicle',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
