# Generated by Django 4.2.11 on 2024-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0008_alter_cameravehicle_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsvehicle',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
