# Generated by Django 4.2.11 on 2024-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0009_alter_gpsvehicle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsvehicle',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
